version: '3'

services:
  postgres:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: civ6_mod
      POSTGRES_PASSWORD: pass
      PGPASSWORD: pswd
      POSTGRES_DB: civ6_mod
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 18080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: tomatono@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:
