FROM node

# shファイルをコンテナにコピー
ADD ./packege_install.sh /workspace/packege_install.sh

# shファイルを実行
# RUN /workspace/packege_install.sh

# # yarn install
# RUN cd /workspace/civ6-utils && yarn install
# RUN cd /workspace/civ6-client && yarn install
# RUN cd /workspace/civ6-server && yarn install

# npm install
# RUN cd /workspace/civ6-utils && npm install
# RUN cd /workspace/civ6-client && npm install
# RUN cd /workspace/civ6-server && npm install

# gitリポジトリのクローン
# RUN cd /workspace && git clone https://github.com/tomatono-git/civ6-apps.git
