version: '3'

services:
  app:
    image: node:17
    container_name: node_app
    tty: true
    volumes:
      - ./workspace:/workspace
    working_dir: "/workspace"
    environment:
      NODE_ENV: development
