version: '3'

services:
  app:
    build: node
    image: node:17
    container_name: node_app
    tty: true
    volumes:
      - ../../civ6-cli/:/workspace/civ6-cli
    working_dir: "/workspace"
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    # command:
    #   npm start
